# .github/workflows/ci.yml
name: CI Build Check

on:
  push:
    branches: [main, desarrollo]
  pull_request:
    branches: [main, desarrollo]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.19.0'

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build
